package leonardo

import (
	"fmt"
	"strconv"
	"strings"
	"time"
)

// LibraryGeneration is one Leonardo-owned generation ready for the desktop
// material library. AssetURLs contains the MP4 for videos (including its audio
// track) or the original image URL for still generations.
type LibraryGeneration struct {
	ID          string
	ModelID     string
	Prompt      string
	Status      string
	CreatedAt   int64
	ImageWidth  int
	ImageHeight int
	AssetURLs   []string
}

// ListRecentGenerations fetches only generations owned by userID. The user
// filter is deliberately mandatory so a public Leonardo feed can never be
// imported into a local account's material library.
func (c *Client) ListRecentGenerations(token, userID string, limit int) ([]LibraryGeneration, error) {
	userID = strings.TrimSpace(userID)
	if userID == "" {
		return nil, fmt.Errorf("leonardo: empty user id for library sync")
	}
	if limit <= 0 {
		limit = 50
	}
	if limit > 200 {
		limit = 200
	}

	op := gqlPayload{
		OperationName: "GetAIGenerationFeed",
		Variables: map[string]any{
			"where": map[string]any{
				"userId": map[string]any{"_eq": userID},
				"teamId": map[string]any{"_is_null": true},
			},
			"limit":  limit,
			"offset": 0,
		},
		Query: `query GetAIGenerationFeed($where: generations_bool_exp = {}, $limit: Int, $offset: Int = 0) {
  generations(
    limit: $limit
    offset: $offset
    order_by: [{createdAt: desc}]
    where: $where
  ) {
    id
    modelId
    coreModel
    prompt
    status
    createdAt
    imageWidth
    imageHeight
    generated_images(order_by: [{url: desc}]) {
      id
      url
      motionGIFURL
      motionMP4URL
      image_width
      image_height
    }
  }
}`,
	}

	resp, err := c.gql(token, op)
	if err != nil {
		return nil, err
	}
	if msg := GraphQLErrorMessage(resp); msg != "" {
		return nil, fmt.Errorf("leonardo: list library: %s", msg)
	}
	return parseLibraryGenerations(resp), nil
}

func parseLibraryGenerations(resp map[string]any) []LibraryGeneration {
	data, _ := resp["data"].(map[string]any)
	rows, _ := data["generations"].([]any)
	out := make([]LibraryGeneration, 0, len(rows))
	for _, row := range rows {
		obj, _ := row.(map[string]any)
		if obj == nil {
			continue
		}
		id := strings.TrimSpace(stringValue(obj["id"]))
		if id == "" {
			continue
		}
		modelID := strings.TrimSpace(stringValue(obj["modelId"]))
		if modelID == "" {
			modelID = strings.TrimSpace(stringValue(obj["coreModel"]))
		}
		width := intValue(obj["imageWidth"])
		height := intValue(obj["imageHeight"])

		assets := make([]string, 0, 4)
		seen := map[string]struct{}{}
		images, _ := obj["generated_images"].([]any)
		for _, rawImage := range images {
			image, _ := rawImage.(map[string]any)
			if image == nil {
				continue
			}
			if width == 0 {
				width = intValue(image["image_width"])
			}
			if height == 0 {
				height = intValue(image["image_height"])
			}
			// Prefer MP4: it is the actual video file and retains the audio
			// generated by models that support sound.
			asset := strings.TrimSpace(stringValue(image["motionMP4URL"]))
			if asset == "" {
				asset = strings.TrimSpace(stringValue(image["url"]))
			}
			if asset == "" {
				asset = strings.TrimSpace(stringValue(image["motionGIFURL"]))
			}
			if asset == "" {
				continue
			}
			if _, ok := seen[asset]; ok {
				continue
			}
			seen[asset] = struct{}{}
			assets = append(assets, asset)
		}

		out = append(out, LibraryGeneration{
			ID:          id,
			ModelID:     modelID,
			Prompt:      stringValue(obj["prompt"]),
			Status:      strings.ToUpper(strings.TrimSpace(stringValue(obj["status"]))),
			CreatedAt:   timestampValue(obj["createdAt"]),
			ImageWidth:  width,
			ImageHeight: height,
			AssetURLs:   assets,
		})
	}
	return out
}

func stringValue(value any) string {
	switch v := value.(type) {
	case string:
		return v
	case fmt.Stringer:
		return v.String()
	case nil:
		return ""
	default:
		return fmt.Sprintf("%v", v)
	}
}

func intValue(value any) int {
	switch v := value.(type) {
	case int:
		return v
	case int64:
		return int(v)
	case float64:
		return int(v)
	case string:
		n, _ := strconv.Atoi(strings.TrimSpace(v))
		return n
	default:
		return 0
	}
}

func timestampValue(value any) int64 {
	switch v := value.(type) {
	case int64:
		return normalizeUnix(v)
	case int:
		return normalizeUnix(int64(v))
	case float64:
		return normalizeUnix(int64(v))
	case string:
		v = strings.TrimSpace(v)
		if v == "" {
			return 0
		}
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			return normalizeUnix(n)
		}
		for _, layout := range []string{time.RFC3339Nano, time.RFC3339, "2006-01-02 15:04:05.999999-07:00"} {
			if parsed, err := time.Parse(layout, v); err == nil {
				return parsed.Unix()
			}
		}
	}
	return 0
}

func normalizeUnix(value int64) int64 {
	if value > 10_000_000_000 {
		return value / 1000
	}
	return value
}
